version: 2
updates:
- package-ecosystem: docker
  directory: "/hack/build/e2e/builder"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/hack/build"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - nberlee
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - "> 1.13.8"
    - "< 2"
  - dependency-name: github.com/coreos/etcd
    versions:
    - "> 3.2.13+incompatible"
