apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etcd-backup-operator
  name: etcd-backup-operator
spec:
  selector:
    matchLabels:
      app: etcd-backup-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd-backup-operator
    spec:
      containers:
      - name: etcd-backup-operator
        image: ghcr.io/on2itsecurity/etcd-operator:v1.2.1
        command:
        - etcd-backup-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
