apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etcd-restore-operator
  name: etcd-restore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-backup-operator
  template:
    metadata:
      labels:
        app: etcd-restore-operator
    spec:
      containers:
      - name: etcd-restore-operator
        image: quay.io/on2itsecurity/etcd-operator:latest
        command:
        - etcd-restore-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
