name: Dockerbase
on:
  push:
jobs:
  buildbase:
    name: docker-base
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code into the Go module directory
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        with:
          config: .github/buildkitd.toml
          version: v0.8.1
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          target: build-base
          push: false
          cache-to: type=gha

