name: Docker image
on:
  pull_request:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        export PATH=$PATH:/home/runner/go/bin

    - name: Build operators
      run: |
        hack/build/operator/build
        hack/build/backup-operator/build
        hack/build/restore-operator/build

    - name: Build image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/etcd-operator:latest -f hack/build/Dockerfile .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image to GPR
      if: github.ref == 'refs/heads/master'
      run: |
        hack/build/docker_push
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
        IMAGE: ghcr.io/${{ github.repository_owner }}/etcd-operator:latest