name: Testing
on:
  push:
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        export PATH=$PATH:/home/runner/go/bin

    - name: Test
      run: go test github.com/on2itsecurity/etcd-operator/pkg/...
