name: Docker image
on:
  workflow_run:
    workflows:
      - Testing E2E
    types:
      - completed
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Check out code into the Go module directory
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: buildx
        with:
          config: .github/buildkitd.toml
          version: v0.11.2
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            ghcr.io/${{ github.repository_owner }}/etcd-operator:latest
            ghcr.io/${{ github.repository_owner }}/etcd-operator:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            REVISION=${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha
